[package]
name          = "tsd"
version       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
authors       = { workspace = true }
description   = "TokenScope daemon"

[[bin]]
name = "tsd"
path = "src/main.rs"

[dependencies]
ts-core             = { workspace = true }
ts-bpf-sys          = { workspace = true }
anyhow              = { workspace = true }
clap                = { workspace = true }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true }
duckdb              = { workspace = true }
ctrlc               = { workspace = true }

[dev-dependencies]
socket2  = "0.5"
tempfile = "3"
