[package]
name          = "tsctl"
version       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
authors       = { workspace = true }
description   = "TokenScope CLI"

[[bin]]
name = "tsctl"
path = "src/main.rs"

[dependencies]
clap       = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
ctrlc      = { workspace = true }
ts-core    = { workspace = true }
tabled     = "0.16"
